id: I1824442D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T16:28:03+00:00'
last_modified: '2022-06-08T05:36:00.513018+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23858
  title: བཟོ་རིག་ཁ་ཤས་ཀྱི་པ་ཏྲ་ལག་ལེན་མ་སོགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    C7C8:
      image_group_id: I6044
      title: ''
      total_pages: 468
      order: 1
      base_file: C7C8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
